### ISSUE TITLE
Verify cards

### ISSUE THREAD

**Issue by Riscky** [svsticky/undead-mongoose#11]
In the current Mongoose backend, cards are validated by sending an email to the member with a validation link.
Board members are also able to verify a card in Koala's admin interface.
This prevents members stealing Mongoose credit by filling in someone else's student number.
We should provide something comparable in undead-mongoose.

This means that 
- Each newly added card should get the status `verified: false`
- Only cards with `verified: true` should be allowed to buy stuff, trying to login to with an unverified card should show a 'please verify, check your email' message (on Sloth)
- There should be a way for an admin to verify a card (section in the interface)
- There should be a way for an user to verify a card. An email with a verification link is probably the best option here, but means adding mail support to undead-mongoose. It would also be possible to build a verification button on the user side, but we don't have a user side yet.

**Comment by Phavion** [comment]
This has been implemented as of cb2ecf280fee33ee7b1ccf98bd0fd67b8169b8e9
