### ISSUE TITLE
Use source-build psycopg2 instead of the binary package

### ISSUE THREAD

**Issue by Riscky** [svsticky/undead-mongoose#14]
According to the psycopg2 docs (https://pypi.org/project/psycopg2-binary):
> The binary package is a practical choice for development and testing but in production it is advised to use the package built from sources.

**Comment by Phavion** [comment]
Sure, we then have to find a way in which for development, we use the binary version and in production the sourced version.

**Comment by Riscky** [comment]
I don't think there's much use to having a separate library for development

**Comment by Riscky** [comment]
This has been obsoleted by using Nix as package manager
