### ISSUE TITLE
Transaction cancellation

### ISSUE THREAD

**Issue by Riscky** [svsticky/undead-mongoose#2]
In the current Mongoose backend we can't cancel transactions. 
It should be possible for an admin to set a recent transaction to 'cancelled' without removing the transaction, since we want to keep logs.
This would be a better way to handle cases where people pay for a product without checking if it is still available first (compared to doing a topup with the same amount).
We probably just want to cancel transactions in the last hour as a security measure.

**Comment by Phavion** [comment]
Do we want top up transactions to be refundable as well? In the sense that we want to keep the refunded top up transactions as well (with just a refunded boolean?)

**Comment by Riscky** [comment]
I think we can just remove / update a top up transaction if an admin realizes it is the wrong amount / person / payment didn't come through
