### ISSUE TITLE
Transaction fails when price is zero.

### ISSUE THREAD

**Issue by TobiasDeBruijn** [svsticky/undead-mongoose#39]
When a price is set to 0.00, when completing a transaction in the transaction overview, the new balance is shown as undefined.
When then purchasing, the transaction fails.

**Comment by Mstiekema** [comment]
Fixed in [#7b1634a3dca6202c758cd4865d1eb028a6baab34](https://github.com/svsticky/magnificent-sloth/pull/87/commits/7b1634a3dca6202c758cd4865d1eb028a6baab34)
