### ISSUE TITLE
Export transactions for accountancy

### ISSUE THREAD

**Issue by JustNireon** [svsticky/undead-mongoose#6]
For our accountancy in ExactOnline we need to import the transactions that have been made everyday.
This is the current endpoint:

```ruby
  def update_transactions
    checkout_transactions = CheckoutTransaction.where('DATE(checkout_transactions.created_at) = DATE(?) AND payment_method = \'Gepind\'', params[:start_date]).order(created_at: :desc)
    data = checkout_transactions.map { |x| { member_id: x.checkout_balance.member.id, name: x.checkout_balance.member.name, price: x.price, date: x.created_at.to_date } }

    render :json => data
  end
``` 

The json needs to be copied to the users clipboard.

**Comment by Phavion** [comment]
At the moment, undead mongoose sends you to a separate page where the json is easily copied. Should be improved by porting it directly to the clipboard. This is however a pain and I had no motivation for it at time of writing :P

**Comment by Mstiekema** [comment]
Has been fixed! We can create exports for Mollie and Pin transactions. Credit card is not included, since the board wants to retire this.
