### ISSUE TITLE
Product VAT percentages

### ISSUE THREAD

**Issue by JustNireon** [svsticky/undead-mongoose#7]
Products have a VAT percentage, at the end of the year the treasurer needs to correct the VAT prices in our accountancy system (exactonline). Normally this is an easy query since alcohol is the only product with 21% VAT. But the new cabinet is looking into increasing the VAT for products with high sugar %. A possible solution would be to give every product a VAT % or per category, but this is up to the programmer.  Furthermore, it would be nice to have some overview where you can see the total price of products bought grouped by VAT Percentage for the treasurer.

**Comment by Phavion** [comment]
Done in a7246d4bbc08127e7c15c2a8851a7bb1e053a826
